# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-29 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_moviedetall_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='电影类型')),
                ('desc', models.CharField(max_length=255, verbose_name='电影类型描述')),
            ],
        ),
        migrations.AddField(
            model_name='moviedetall',
            name='kind',
            field=models.ManyToManyField(to='movie.MovieKind'),
        ),
    ]
